version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: capr1-site-container
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      STAGE: "production"
      DOMAINS: >-
        www.capr1.site
    volumes:
      - ./src:/var/www/vhosts/www.capr1.site
      - /data/ssl_certs:/var/lib/https-portal
