apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: capr1-site
  namespace: capr1-site
spec:
  selector:
    matchLabels:
      name: capr1-site
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        name: capr1-site
    spec:
      containers:
        - name: capr1-site
          image: capr1/cape1-site:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: capr1-site
  namespace: capr1-site
  labels:
    name: capr1-site
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    name: capr1-site
  type: LoadBalancer
---

